
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
   
    firebase_app_distribution(
        app: "1:940046231017:android:dd6d7394002c8dc8635778",
        firebase_cli_token: "1//03yVhTG9IeX8oCgYIARAAGAMSNwF-L9IrlN0nRXEvkB2RH5w7uZ7DtaeKBZ0EctzOGykBcjSEIZX53Y0mtf3h0itnIhbxb7p7QtY",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mohammadwork199700@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end
